name: DTU Notice Checker

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch:       # manual run from GitHub UI

jobs:
  check-notices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run notice checker
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm start